name: "mjpg-streamer"
version: "2022.7.001"
slug: "camera-mjpg-streamer"
description: "Camera streaming addon for Home Assistant, based on mjpg-streamer."
url: "https://github.com/fredrikbaberg/3dprinter-addons/tree/main/camera-mjpg-streamer"
ingress: true
ingress_stream: true
panel_icon: mdi:camera
panel_title: mjpg-streamer
arch:
    - armv7
    - amd64
    - armhf
    - aarch64
    - i386
init: false
video: true
usb: true
ports:
    8000/tcp: null
ports_description:
    8000/tcp: Web-based interface (Not required for Ingress)
options:
    mjpg_input: "input_uvc.so -n"
schema:
    mjpg_input: "str"
image: ghcr.io/fredrikbaberg/addon-camera-mjpg-streamer-{arch}
